In [86]:
import pandas as pd
df = pd.read_csv("data_Florida_2005_2015._10.csv")
df

,average_demand,Number_of_energy_intensive_industry,no_of energy_non_intensive_industry,gdp_growth,load_share,average_retail_sales
0,7556.666667,7083,10701,0.991235,28.887077,8.280000
1,9007.666667,7078,10630,1.011899,34.783560,5.906667
2,9893.000000,7110,10680,2.858836,34.050389,6.446667
3,9475.333333,7120,10642,3.336576,26.812428,7.503333
4,7496.333333,6902,8772,2.660160,29.272261,7.563333
5,7452.666667,6951,8815,2.166866,30.728000,7.793333
6,7871.333333,6953,8834,1.387530,27.643609,7.720000
7,8224.000000,6952,8821,1.757886,23.992065,7.863333
8,8141.666667,7528,9067,1.644722,30.726749,7.733333
9,7255.000000,7556,9098,3.777497,28.298207,7.750000
10,7692.666667,7598,9095,1.209821,29.199722,7.893333
11,8436.000000,7588,9061,1.882091,25.606573,7.720000
12,7807.000000,7476,8868,0.942279,30.132774,8.496667
13,8322.666667,7512,8875,3.103232,30.762786,8.053333
14,9329.666667,7536,8884,0.260265,31.398571,9.183333
15,8934.000000,7522,8860,-3.814182,26.022117,9.596667
16,7140.666667,7521,8836,-3.951231,28.274642,6.620000
17,6867.333333,7460,8793,-1.746163,27.665946,7.816667
18,7138.000000,7440,8715,0.888989,27.093640,7.050000
19,7627.333333,7413,8674,2.263538,22.631022,6.593333
20,7810.333333,7371,10818,3.283483,29.562200,6.096667
21,7140.666667,7353,10757,0.205198,25.967005,6.616667
22,7877.333333,7359,10723,1.634963,28.042196,6.490000
23,8759.666667,7404,10735,2.025173,24.137298,6.476667
24,7719.000000,7440,10818,2.553860,28.835952,6.006667
25,7632.333333,7484,10812,2.493709,27.419587,6.170000
26,8285.333333,7480,10832,1.145222,27.433970,6.180000
27,8480.000000,7514,10850,2.106908,22.289004,6.923333
28,7655.666667,7530,10892,2.413309,27.402670,5.713333
29,7254.666667,7491,10824,0.426279,27.769413,5.753333
30,7532.333333,7497,10823,1.271439,25.524393,5.580000
31,8052.000000,7547,10805,2.518664,21.945037,5.990000
32,7677.000000,7558,10821,1.705377,26.457816,5.856667
33,7152.000000,7577,10839,1.551181,26.470262,5.633333
34,7847.000000,7579,10853,1.911327,26.636418,5.940000
35,8120.000000,7603,10826,0.941153,22.137606,6.223333
36,8106.000000,7658,10891,0.728783,27.890813,6.220000
37,7799.333333,7682,10878,2.085869,25.337044,6.103333
38,8658.333333,7724,10926,1.686529,28.809254,5.963333
39,8634.333333,7767,10959,-0.834341,23.284014,6.376667
40,8630.000000,7847,11082,-0.315434,29.129163,5.260000
41,7687.333333,7847,11122,0.024498,25.699831,5.806667
42,8474.666667,7855,11100,-0.603652,28.225994,5.493333
43,9052.000000,7869,11091,-1.188568,23.360402,5.596667

Index(['average_demand', 'Number_of_energy_intensive_industry',
       'no_of energy_non_intensive_industry', 'gdp_growth', 'load_share',
       'average_retail_sales'],
      dtype='object')

2734

In [1]:
from sklearn import preprocessing
mms = preprocessing.MinMaxScaler()
minmax = mms.fit_transform(df)
print(minmax)
labels =['avg_demand','Number_of_energy_intensive_industry','Number_of_energy_non_intensive_industry','gdp_growth','load_share','average_retail_sales']
df1 = pd.DataFrame.from_records(minmax, columns=labels)
df1.to_csv("norm_data_Florida_2005_2015_10.csv", sep="\t")

NameError: name 'df' is not defined